CREATE VIEW INSURIT.PENDING_CLAIMS AS
SELECT
    PH.CUSTOMER_ID,
    COALESCE(REJCT.CNT, 0) AS PAST_REJECTS,
    CLAIM_ID,
    C.DATE AS CLAIM_DT,
    CLAIM_AMOUNT,
    STATUS_OF_POLICY AS POLICY_STATUS,
    AT_RISK_FLAG AS POLICY_AT_RISK,
    AGENT_ID
FROM
    INSURIT.CLAIM C
INNER JOIN INSURIT.POLICY_HOLDER PH ON PH.HOLDER_ID = C.HOLDER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS CNT
    FROM
        INSURIT.CLAIM C1
    INNER JOIN INSURIT.POLICY_HOLDER PH1 ON PH1.HOLDER_ID = C1.HOLDER_ID
    WHERE
        CLAIM_STATUS = 'R'
    GROUP BY
        CUSTOMER_ID
) REJCT ON REJCT.CUSTOMER_ID = PH.CUSTOMER_ID
WHERE
    CLAIM_STATUS = 'P';
COMMIT;