INSERT INTO AutoPolicy_detail VALUES (111,'Comprehensive Car Care','Sedan','This policy covers all types of sedans and offers comprehensive protection, including coverage for accidents, theft, natural disasters, and medical expenses.','Active',50000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (112,'Off-Road Adventure Shield','SUV','Designed for SUVs and off-road vehicles, this policy provides specialized coverage for damages incurred during off-road adventures, including collisions, rollovers, and towing expenses.','Active',70000,24,'Auto');
INSERT INTO AutoPolicy_detail VALUES (113,'Oriental Motor Plan','Motorbike','Tailored for motorcycles, this policy covers damages resulting from accidents, theft, and third-party liabilities, ensuring the freedom of the open road with peace of mind.','Active',30000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (114,'Classic Car Elegance','Vintage Cars','Geared towards vintage and classic cars, this policy offers extensive coverage for restoration costs, market value, and special roadside assistance, preserving the elegance of your cherished automobile.','Inactive',100000,60,'Auto');
INSERT INTO AutoPolicy_detail VALUES (115,'Electric Vehicle EcoShield','Electric Cars','Tailored for electric cars, this policy covers battery damage, charging equipment, and specialized repairs, promoting eco-friendly driving with dedicated insurance support.','Active',60000,24,'Auto');
INSERT INTO AutoPolicy_detail VALUES (116,'Family safety plan','Sedan','This policy emphasizes safety, covering child seat replacements, medical expenses for passengers, and roadside assistance for families on the go.','Active',50000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (117,'Luxury Sedan Prestige Coverage','Sedan','Catering to luxury sedans, this policy offers specialized coverage for high-end interiors, technology systems, and concierge services, ensuring that every aspect of your luxury driving experience is protected','Active',100000,24,'Auto');
INSERT INTO AutoPolicy_detail VALUES (118,'SafeDrive','Motorbike','Premium policy offering high coverage limits, including coverage for uninsured motorists and roadside assistance.','Active',100000,24,'Auto');
INSERT INTO AutoPolicy_detail VALUES (119,'Guardian Auto Insurance','Electric Cars','Short-term policy with comprehensive coverage, ideal for temporary needs such as rental cars or seasonal driving.','Inactive',60000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (120,'DriveSure Insuranc','SUV','Policy tailored for frequent travelers, offering coverage for rental cars and drivers in multiple states.','Active',80000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (121,'Liberty Auto Assurance','Sedan & SUV','Standard coverage for collisions and comprehensive damages, with optional add-ons for enhanced protection.','Active',50000,12,'Auto');
INSERT INTO AutoPolicy_detail VALUES (122,'ABC Plan','Sedan & SUV','Basic coverage for liability and medical expenses, suitable for low-risk drivers.','Inactive',40000,12,'Auto');

Select * from autopolicy_detail;