use INSURIT;
DELIMITER //
CREATE TRIGGER generate_credentials
AFTER INSERT ON INSURIT.CUSTOMER
FOR EACH ROW
BEGIN
    DECLARE hashed VARCHAR(255);
    SET hashed = SHA2(LOWER(NEW.NAME), 256);

    INSERT INTO INSURIT.SECRETS (id, USERNAME, SECRET)
    VALUES (NEW.Customer_id, SUBSTRING_INDEX(NEW.NAME, ' ', 1), hashed);
END;
//
CREATE TRIGGER generate_agent_credentials
AFTER INSERT ON INSURIT.AGENTS
FOR EACH ROW
BEGIN
    DECLARE hashed VARCHAR(255);
    SET hashed = SHA2(LOWER(NEW.NAME), 256);

    INSERT INTO INSURIT.SECRETS (id, USERNAME, SECRET)
    VALUES (NEW.Agent_id, SUBSTRING_INDEX(NEW.NAME, ' ', 1), hashed);
END;
//
DELIMITER ;
COMMIT;