use insurit;
INSERT INTO HomePolicy_detail VALUES (100,'HomeShield','Rent and Owned','Comprehensive coverage for the structure of the home, personal belongings, liability protection, and additional living expenses in case of temporary displacement due to covered events.','Active',300000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (101,'SecureHome','Owned','Premium policy offering high coverage limits, including protection against natural disasters, theft, and personal injury liability, with options for custom add-ons.','Active',500000,24,'Home');
INSERT INTO HomePolicy_detail VALUES (102,'SafeHaven Insurance','Rent and Owned','Basic coverage for the homes structure and essential belongings, suitable for homeowners seeking affordable protection against common risks.','Active',250000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (103,'Liberty Home Protection','Owned','Standard policy covering damages from fire, vandalism, and certain natural disasters, along with liability coverage for accidents on the property.','Inactive',400000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (104,'EverGuard Home Insurance','Owned','Long-term coverage with benefits like extended replacement cost, which ensures the home can be rebuilt to its original condition even if construction costs rise.','Active',350000,36,'Home');
INSERT INTO HomePolicy_detail VALUES (105,'Guardian Home Assurance','Rent and Owned','Policy offering protection against various perils, including water damage, mold, and coverage for high-value items like jewelry and artwork.','Active',200000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (106,'National Home Protection','Rent','Short-term policy ideal for renters, offering coverage for personal belongings, liability, and temporary living expenses in case of covered events.','Active',100000,24,'Home');
INSERT INTO HomePolicy_detail VALUES (107,'Reliable Home Insurance','Owned','Policy tailored for homeowners with additional structures on their property, such as detached garages or sheds, providing coverage for both the main home and other structures.','Active',100000,24,'Home');
INSERT INTO HomePolicy_detail VALUES (108,'SmartGuard Home Insurance','Owned','Customizable policy allowing homeowners to choose specific coverage limits and endorsements to protect unique assets and accommodate individual needs.','Inactive',350000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (109,'SafeHome Solutions','Owned','High-value policy with features like identity theft protection, credit card coverage, and coverage for unauthorized transactions due to cybercrime.','Active',555000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (110,'HomeAssure Services','Rent','Policy offering coverage for home systems and appliances, such as HVAC, electrical, and plumbing, providing financial protection against unexpected repair or replacement costs.','Active',400000,12,'Home');
INSERT INTO HomePolicy_detail VALUES (123,'One Home Insurance','Owned','Long-term policy with perks like extended coverage for valuables, home office equipment, and reimbursement for temporary housing and meals during repairs.','Inactive',250000,12,'Home');

commit;
